version: 0.2

phases:
  build:
    commands:
      - echo Build started on `date`
      - mvn test
  post_build:
    commands:
      - echo Build completed on `date`
      - mvn package
      - mv target/*.jar .
      - mv newrelic/newrelic.yml newrelic.yml
artifacts:
  discard-paths: no
  files:
    - application.jar
    - newrelic.jar
    - newrelic.yml
    - Procfile
    - .ebextensions/*